# Bot Configuration
owner_id: id
telegram_token: "token"
btc_wallet_address: "btc address"

# Messages
messages:
  welcome_to_bot: |
    Welcome {username} to the bot!
    Enjoy your stay.
    Feel free to browse the shop.
  shop_title: "ğŸ›’ Shop"
  no_products_available: "ğŸ˜¢ No products available."
  add_product: "ğŸ†• Add a new product. Send the product name."
  add_product_price: "ğŸ’² Send the product price."
  add_product_file: "ğŸ“ Send the product file."
  product_added: "âœ… Product successfully added."
  invalid_file_type: "âŒ Invalid file type."
  no_document_attached: "â— No document attached."
  this_product_is_no_longer_available: "âŒ This product is no longer available."
  an_error_occurred: "â— An error occurred."
  insufficient_balance: "ğŸ’¸ Insufficient balance."
  btc_address_sent: "ğŸ“¬ BTC address sent. You can now copy it."
  profile_info: "ğŸ‘¤ Username: {username}\nğŸ’° Balance: {balance}"
  error_fetching_profile: "â— Error fetching profile."
  no_transaction_found: "âš ï¸ No transaction found in the last hour."
  error_occurred: "â— An error occurred."
  notifications_status: "ğŸ”” Notifications are {status}."
  please_send_new_admin_id: "ğŸ‘¤ Send the new admin ID."
  admin_added: "ğŸ‘‘ New admin added: {new_admin_id}."
  you_do_not_have_permission_to_add_admin: "â— You do not have permission to add a new admin."
  you_do_not_have_permission_to_access: "ğŸš« You do not have permission to access."
  admin_panel_title: "ğŸ›  Admin Panel."
  products_list: "ğŸ“¦ Here is the list of available products ğŸ“¦"
  admin_list_title: "ğŸ‘¥ Admin List."
  revoked_admin_permission: "ğŸš« Admin permission revoked for {admin_id_to_revoke}."
  transaction_verified: "âœ… Transaction verified. Amount added: {amount_in_usd}."
  btc_wallet_added: "ğŸ”’ BTC wallet address added."
  please_send_btc_wallet: "ğŸ”’ Send your BTC address."
  wallet_already_added: "You have already added a wallet address."
  deposit_message: "ğŸ’° To deposit, send BTC to the following address: {btc_wallet_address}"
  product_purchased_successfully: "ğŸ›’ Product {product_name} successfully purchased. Current balance: {new_balance}"
  welcome_back_message: |
    ğŸ‘‹ Welcome back, {username}!
    We missed you.
    Feel free to continue shopping.
    Your current balance is {balance}

# Buttons
buttons:
  view_profile: "ğŸ‘¤ View Profile"
  view_shop: "ğŸ›’ View Shop"
  download_file: "ğŸ“¥ Download File"
  back_to_products_list: "ğŸ”™ Back to Products List"
  delete_product: "ğŸ—‘ï¸ Delete Product"
  confirm_delete: "âœ… Confirm Delete"
  cancel_delete: "âŒ Cancel Delete"
  buy_product: "ğŸ›’ Buy Product"
  add_product: "ğŸ†• Add Product"
  confirm_purchase: "âœ… Confirm Purchase"
  cancel_purchase: "âŒ Cancel Purchase"
  deposit: "ğŸ’° Deposit"
  copy_btc_address: "ğŸ“‹ Copy BTC Address"
  verify_transaction: "âœ… Verify Transaction"
  add_wallet_address: "ğŸ”’ Add BTC Address"
  main_menu: "ğŸ  Main Menu"
  show_products_list: "ğŸ“¦ Show Products List"
  disable_notifications: "ğŸ”• Disable Notifications"
  enable_notifications: "ğŸ”” Enable Notifications"
  back_to_profile: "ğŸ”™ Back to Profile"
  back_to_main_menu: "ğŸ  Back to Main Menu"
  back_to_admin_panel: "ğŸ›  Back to Admin Panel"
  admin_panel: "ğŸ›  Admin Panel"
  add_new_admin: "ğŸ‘‘ Add New Admin"
  show_admin_list: "ğŸ‘¥ Show Admin List"
